<?php $apps=$workspace['applications']; require __DIR__.'/layout/start.php'; ?>
<main class="shell">
  <section class="company-hero"><div><a class="back" href="companyFile.php">← 企業一覧</a><span class="eyebrow"><?=h($company['industry_name']??'INDUSTRY UNSET')?></span><h1><?=h($company['name'])?></h1><p><?=h($company['business']??'事業内容は未登録です。')?></p></div><div class="hero-actions"><?php if($company['corporate_url']):?><a class="button" target="_blank" rel="noopener" href="<?=h($company['corporate_url'])?>">企業サイト</a><?php endif;?><a class="button primary" href="campe.php?company_id=<?=$company['company_id']?>&application_id=<?=(int)($apps[0]['application_id']??0)?>">面接モード</a></div></section>
  <nav class="tabs"><a href="#applications">応募</a><a href="#flow">選考</a><a href="#prep">面接対策</a><a href="#notes">メモ・ログ</a><a href="#resources">資料</a></nav>
  <section class="panel"><div class="section-head"><div><span class="eyebrow">SCHEDULE & TASKS</span><h2>直近の予定・タスク</h2></div><div class="hero-actions"><button class="button" type="button" data-dialog-open="task-dialog">タスクを追加</button><button class="button" type="button" data-dialog-open="event-dialog">予定を追加</button></div></div><div class="schedule-grid"><div><h3>予定</h3><div class="stack"><?php foreach($workspace['events'] as $row):?><article class="list-card"><span class="status doing"><?=h($row['event_type'])?></span><span><strong><?=h($row['title'])?></strong><small><?=h(fmt_datetime($row['start_at']))?><?=!empty($row['location'])?' / '.h($row['location']):''?></small></span></article><?php endforeach;?><?php if(!$workspace['events']):?><p class="empty">予定はありません。</p><?php endif;?></div></div><div><h3>タスク</h3><div class="stack"><?php foreach($workspace['tasks'] as $row):?><article class="list-card task-row"><span class="status todo"><?=h(fmt_datetime($row['due_at']))?></span><span class="task-main"><strong><?=h($row['title'])?></strong><small><?=h($row['application_title']??'企業共通')?></small></span><form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="complete_task"><input type="hidden" name="task_id" value="<?=$row['task_id']?>"><button class="button small" type="submit">完了</button></form></article><?php endforeach;?><?php if(!$workspace['tasks']):?><p class="empty">タスクはありません。</p><?php endif;?></div></div></div></section>
  <section class="panel" id="applications"><div class="section-head"><div><span class="eyebrow">APPLICATIONS</span><h2>応募案件</h2></div><button class="button" type="button" data-dialog-open="application-dialog">応募を追加</button></div>
    <div class="application-grid"><?php foreach($apps as $app):?><article class="application-card"><div class="section-head"><span class="status <?=$app['rejected']?'danger':'doing'?>"><?=h($app['status_name']??'未設定')?></span><strong><?=h($app['interest_name']??'志望度未設定')?></strong></div><h3><?=h($app['title'])?></h3><p><?=h($app['job_name']??'職種未設定')?><?=!empty($app['agent_name'])?' / '.h($app['agent_name']):''?></p><dl><dt>次のアクション</dt><dd><?=h($app['next_action']??'-')?></dd><dt>締切</dt><dd><?=h(fmt_datetime($app['deadline_at']))?></dd></dl><?php if($app['mypage_url']):?><a class="text-link" target="_blank" rel="noopener" href="<?=h($app['mypage_url'])?>">マイページを開く</a><?php endif;?></article><?php endforeach;?><?php if(!$apps):?><p class="empty">応募案件を登録してください。</p><?php endif;?></div>
  </section>
  <section class="panel" id="flow"><div class="section-head"><div><span class="eyebrow">SELECTION FLOW</span><h2>選考フロー</h2></div><button class="button" type="button" data-dialog-open="step-dialog">ステップを追加</button></div>
    <div class="timeline"><?php foreach($workspace['steps'] as $step):?><article class="timeline-item <?=$step['status']?>"><div class="dot"></div><div class="timeline-card"><div class="section-head"><span class="status <?=$step['status']?>"><?=h($step['status'])?></span><small><?=h($step['application_title'])?></small></div><h3><?=h($step['title'])?></h3><p><?=h($step['memo']??'')?></p><div class="meta"><span>予定 <?=h(fmt_datetime($step['scheduled_at']))?></span><span>締切 <?=h(fmt_datetime($step['deadline_at']))?></span></div><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="step_status"><input type="hidden" name="step_id" value="<?=$step['step_id']?>"><select class="field small" name="status"><option value="todo" <?=$step['status']==='todo'?'selected':''?>>未着手</option><option value="doing" <?=$step['status']==='doing'?'selected':''?>>進行中</option><option value="done" <?=$step['status']==='done'?'selected':''?>>完了</option></select><button class="button small" type="submit">更新</button></form></div></article><?php endforeach;?><?php if(!$workspace['steps']):?><p class="empty">選考フローはまだありません。</p><?php endif;?></div>
  </section>
  <div class="dashboard-grid">
    <section class="panel" id="prep"><div class="section-head"><h2>面接対策</h2><button class="button" type="button" data-dialog-open="content-dialog">追加</button></div><div class="stack"><?php foreach($workspace['contents'] as $row):?><article class="content-card"><span class="status"><?=h($row['category'])?></span><h3><?=h($row['title'])?></h3><p><?=nl2br(h(mb_strimwidth($row['body'],0,260,'…')))?></p></article><?php endforeach;?><?php if(!$workspace['contents']):?><p class="empty">自己PRや逆質問を登録できます。</p><?php endif;?></div></section>
    <section class="panel" id="notes"><div class="section-head"><h2>メモ・面接ログ</h2><button class="button" type="button" data-dialog-open="note-dialog">メモを追加</button></div><div class="stack"><?php foreach(array_merge($workspace['notes'],$workspace['logs']) as $row):?><article class="content-card"><span class="status"><?=h($row['category']??'面接ログ')?></span><h3><?=h($row['title'])?></h3><p><?=nl2br(h(mb_strimwidth($row['body'],0,220,'…')))?></p></article><?php endforeach;?><?php if(!$workspace['notes']&&!$workspace['logs']):?><p class="empty">メモと面接ログはまだありません。</p><?php endif;?></div></section>
  </div>
  <section class="panel" id="resources"><div class="section-head"><div><span class="eyebrow">RESOURCES</span><h2>資料・外部リンク</h2></div><button class="button" type="button" data-dialog-open="resource-dialog">資料を追加</button></div><div class="resource-grid"><?php foreach($workspace['resources'] as $row):?><a class="resource-card" target="_blank" rel="noopener" href="<?=$row['resource_type']==='upload'?'download.php?id='.(int)$row['resource_id']:h($row['external_url'])?>"><span class="file-icon"><?=$row['resource_type']==='upload'?'DOC':'LINK'?></span><strong><?=h($row['display_name'])?></strong><small><?=h($row['category'])?></small></a><?php endforeach;?><?php if(!$workspace['resources']):?><p class="empty">文章ファイルまたはGoogle Drive等のリンクを登録できます。</p><?php endif;?></div></section>
</main>

<?php
$dialogs=[
 ['application-dialog','応募案件を追加','add_application'],
 ['step-dialog','選考ステップを追加','add_step'],
 ['content-dialog','面接対策を追加','add_content'],
 ['note-dialog','メモを追加','add_note'],
 ['event-dialog','予定を追加','add_event'],
 ['task-dialog','タスクを追加','add_task'],
];
foreach($dialogs as [$id,$title,$action]): ?>
<dialog id="<?=$id?>" class="dialog"><form method="post" class="form-stack"><div class="section-head"><h2><?=$title?></h2><button class="icon-button" type="button" data-dialog-close>×</button></div><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="<?=$action?>">
<?php if($action==='add_application'):?><label>応募名<input class="field" name="title" placeholder="新卒採用 / エンジニア職" required></label><label>職種<select class="field" name="job_category_id"><option value="">未設定</option><?php foreach($masters['jobs'] as $r):?><option value="<?=$r['job_category_id']?>"><?=h($r['name'])?></option><?php endforeach;?></select></label><label>志望度<select class="field" name="interest_level_id"><option value="">未設定</option><?php foreach($masters['interests'] as $r):?><option value="<?=$r['interest_level_id']?>"><?=h($r['name'])?></option><?php endforeach;?></select></label><label>状況<select class="field" name="status_id"><option value="">未設定</option><?php foreach($masters['statuses'] as $r):?><option value="<?=$r['status_id']?>"><?=h($r['name'])?></option><?php endforeach;?></select></label><label>応募経路<select class="field" name="source_id"><option value="">未設定</option><?php foreach($masters['sources'] as $r):?><option value="<?=$r['source_id']?>"><?=h($r['name'])?></option><?php endforeach;?></select></label><label>担当エージェント<select class="field" name="agent_id"><option value="">未設定</option><?php foreach($masters['agents'] as $r):?><option value="<?=$r['agent_id']?>"><?=h($r['name'])?></option><?php endforeach;?></select></label><label>マイページURL<input class="field" type="url" name="mypage_url"></label><label>締切<input class="field" type="datetime-local" name="deadline_at"></label><label>次のアクション<input class="field" name="next_action"></label><label>志望動機<textarea class="field tall" name="motivation"></textarea></label>
<?php elseif($action==='add_step'):?><label>応募案件<select class="field" name="application_id" required><?php foreach($apps as $r):?><option value="<?=$r['application_id']?>"><?=h($r['title'])?></option><?php endforeach;?></select></label><label>ステップ名<input class="field" name="title" placeholder="説明会 / ES提出 / 一次面接" required></label><label>種類<select class="field" name="step_type"><option value="briefing">説明会</option><option value="es">ES提出</option><option value="test">適性検査</option><option value="interview">面接</option><option value="offer">内定</option><option value="step">その他</option></select></label><label>予定<input class="field" type="datetime-local" name="scheduled_at"></label><label>締切<input class="field" type="datetime-local" name="deadline_at"></label><label>メモ<textarea class="field" name="memo"></textarea></label>
<?php elseif($action==='add_content'):?><label>応募案件<select class="field" name="application_id"><option value="">企業共通</option><?php foreach($apps as $r):?><option value="<?=$r['application_id']?>"><?=h($r['title'])?></option><?php endforeach;?></select></label><label>分類<select class="field" name="category"><option value="self_pr">自己PR</option><option value="gakuchika">ガクチカ</option><option value="motivation">志望動機</option><option value="questions">逆質問</option><option value="cheat">カンペ</option></select></label><label>タイトル<input class="field" name="title" required></label><label>本文<textarea class="field tall" name="body" required></textarea></label><label class="check"><input type="checkbox" name="interview_visible" checked> 面接モードに表示</label>
<?php elseif($action==='add_note'):?><label>応募案件<select class="field" name="application_id"><option value="">企業共通</option><?php foreach($apps as $r):?><option value="<?=$r['application_id']?>"><?=h($r['title'])?></option><?php endforeach;?></select></label><label>分類<select class="field" name="category"><option value="briefing">説明会</option><option value="agent">エージェント面談</option><option value="practice">面接練習</option><option value="company_research">企業研究</option></select></label><label>タイトル<input class="field" name="title" required></label><label>本文<textarea class="field tall" name="body" required></textarea></label>
<?php elseif($action==='add_event'):?><label>状態<select class="field" name="schedule_status"><option value="confirmed">確定予定</option><option value="tentative">仮予定</option></select></label><label>応募案件<select class="field" name="application_id"><option value="">企業共通</option><?php foreach($apps as $r):?><option value="<?=$r['application_id']?>"><?=h($r['title'])?></option><?php endforeach;?></select></label><label>種類<select class="field" name="event_type"><option value="interview">面接</option><option value="briefing">説明会</option><option value="deadline">締切</option><option value="other">その他</option></select></label><label>タイトル<input class="field" name="title" required></label><label>開始日時<input class="field" type="datetime-local" name="start_at" required></label><label>終了日時<input class="field" type="datetime-local" name="end_at"></label><label>場所<input class="field" name="location"></label><label>URL<input class="field" type="url" name="url"></label><label>メモ<textarea class="field" name="memo"></textarea></label>
<?php else:?><label>応募案件<select class="field" name="application_id"><option value="">企業共通</option><?php foreach($apps as $r):?><option value="<?=$r['application_id']?>"><?=h($r['title'])?></option><?php endforeach;?></select></label><label>タスク名<input class="field" name="title" required></label><label>期限<input class="field" type="datetime-local" name="due_at"></label><?php endif;?><button class="button primary" type="submit">保存</button></form></dialog><?php endforeach;?>
<dialog id="resource-dialog" class="dialog"><form action="resources.php?company_id=<?=$company['company_id']?>" method="post" enctype="multipart/form-data" class="form-stack"><div class="section-head"><h2>資料を追加</h2><button class="icon-button" type="button" data-dialog-close>×</button></div><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><label>表示名<input class="field" name="display_name" required></label><label>関連応募<select class="field" name="application_id"><option value="">企業共通</option><?php foreach($apps as $r):?><option value="<?=$r['application_id']?>"><?=h($r['title'])?></option><?php endforeach;?></select></label><label>分類<select class="field" name="category"><option value="es">ES</option><option value="resume">履歴書・職務経歴書</option><option value="portfolio">ポートフォリオ</option><option value="company_material">企業資料</option><option value="other">その他</option></select></label><label>登録方法<select class="field" name="resource_type" data-resource-type><option value="external">外部共有リンク</option><option value="upload">文章ファイルをアップロード</option></select></label><label data-external-field>HTTPS共有URL<input class="field" type="url" name="external_url" placeholder="https://drive.google.com/..."></label><label data-upload-field hidden>PDF・Word・テキスト（最大10MB）<input class="field" type="file" name="document" accept=".pdf,.doc,.docx,.txt"></label><button class="button primary" type="submit">登録</button></form></dialog>
<?php require __DIR__.'/layout/end.php'; ?>
