<?php require __DIR__.'/layout/start.php'; ?>
<main class="shell">
  <section class="hero compact"><div><span class="eyebrow"><?=$archived?'ARCHIVE':'COMPANIES'?></span><h1><?=$archived?'過去企業':'企業・応募管理'?></h1><p><?=$archived?'終了した企業を最小表示で保管します。':'応募案件は必要になった時だけ追加できます。'?></p></div><div class="hero-actions"><a class="button" href="companyFile.php<?=$archived?'':'?archived=1'?>"><?=$archived?'通常企業へ':'過去企業一覧'?></a></div></section>
  <div class="split">
    <section class="panel grow">
      <form class="search" method="get"><input class="field" name="q" value="<?=h($q)?>" placeholder="企業名・事業内容を検索"><button class="button" type="submit">検索</button></form>
      <div class="company-grid"><?php foreach($companies as $row):?><a class="company-card" href="company.php?id=<?=(int)$row['company_id']?>"><div class="company-icon"><?=h(mb_substr($row['name'],0,1))?></div><div><h2><?=h($row['name'])?></h2><p><?=h($row['industry_name']??'業界未設定')?></p><div class="meta"><span>応募 <?=h($row['application_count'])?>件</span><span>締切 <?=h(fmt_datetime($row['next_deadline']))?></span></div></div><span class="arrow">›</span></a><?php endforeach;?><?php if(!$companies):?><p class="empty">企業が登録されていません。</p><?php endif;?></div>
    </section>
    <aside class="side-stack"><section class="panel" id="new-company" data-tutorial-target="company-form"><h2>企業を登録</h2><form method="post" class="form-stack"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="add_company"><?php if($tutorialStage==='company'):?><input type="hidden" name="tutorial_stage" value="company"><?php endif;?><label>企業名<input class="field" name="name" required></label><label>業界<select class="field" name="industry_id"><option value="">未設定</option><?php foreach($masters['industries'] as $row):?><option value="<?=$row['industry_id']?>"><?=h($row['name'])?></option><?php endforeach;?></select></label><label>企業URL<input class="field" type="url" name="corporate_url" placeholder="https://"></label><label>事業内容<textarea class="field" name="business"></textarea></label><label>メモ<textarea class="field" name="memo"></textarea></label><button class="button primary" type="submit" data-tutorial-target="company-save">登録する</button></form></section><section class="panel" id="masters"><h2>分類・担当者を追加</h2><form method="post" class="form-stack"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="add_master"><label>分類<select class="field" name="master_type"><option value="industry">業界</option><option value="job">職種</option><option value="interest">志望度</option><option value="status">応募状況</option><option value="source">応募経路</option></select></label><label>名称<input class="field" name="master_name" required></label><button class="button" type="submit">分類を追加</button></form><hr><form method="post" class="form-stack"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="add_agent"><label>エージェント名<input class="field" name="agent_name" required></label><button class="button" type="submit">担当者を追加</button></form></section></aside>
  </div>
</main>
<?php if($tutorialStage==='company')require __DIR__.'/partials/tutorial_company.php';?>
<?php require __DIR__.'/layout/end.php'; ?>
