<?php require __DIR__.'/layout/start.php'; ?>
<main class="shell">
  <section class="hero">
    <div><span class="eyebrow">TODAY</span><h1>今日のオペレーション</h1><p>予定、締切、次の選考をここから処理できます。</p></div>
    <div class="hero-actions"><button class="button" type="button" data-dialog-open="task-dialog">タスクを登録</button><a class="button primary" href="companyFile.php#new-company">企業を登録</a></div>
  </section>
  <div class="metric-grid">
    <article class="metric"><strong><?=count($events)?></strong><span>今日の予定</span></article>
    <article class="metric"><strong><?=count($deadlines)?></strong><span>直近の締切</span></article>
    <article class="metric"><strong><?=count($nextSteps)?></strong><span>未完了の選考</span></article>
    <article class="metric"><strong><?=count($recentNotes)?></strong><span>最近のメモ</span></article>
  </div>
  <div class="dashboard-grid">
    <section class="panel"><div class="section-head"><h2>今日の予定</h2></div>
      <div class="stack"><?php foreach($events as $row): ?><a class="list-card" href="<?=!empty($row['company_id'])?'company.php?id='.(int)$row['company_id']:'#calendar'?>"><span class="time"><?=h(substr($row['start_at'],11,5))?></span><span><strong><?=h($row['title'])?></strong><small><?=h($row['company_name']??'個人予定')?><?=!empty($row['application_title'])?' / '.h($row['application_title']):''?></small></span></a><?php endforeach; ?><?php if(!$events):?><p class="empty">今日の予定はありません。</p><?php endif;?></div>
    </section>
    <section class="panel"><div class="section-head"><h2>直近の締切</h2></div>
      <div class="stack"><?php foreach($deadlines as $row): ?><a class="list-card" href="<?=$row['company_id']?'company.php?id='.(int)$row['company_id']:'#'?>"><span class="status danger"><?=h(substr($row['deadline_at'],5,11))?></span><span><strong><?=h($row['company_name']??'個人タスク')?></strong><small><?=h($row['item_type'])?> / <?=h($row['title'])?></small></span></a><?php endforeach;?><?php if(!$deadlines):?><p class="empty">締切は登録されていません。</p><?php endif;?></div>
    </section>
    <section class="panel wide"><div class="section-head"><h2>次の選考</h2></div>
      <div class="flow-row"><?php foreach($nextSteps as $row): ?><a class="flow-card" href="company.php?id=<?=(int)$row['company_id']?>"><span class="status <?=h($row['status'])?>"><?=h($row['status'])?></span><strong><?=h($row['title'])?></strong><small><?=h($row['company_name'])?> / <?=h($row['application_title'])?></small><span><?=h(fmt_datetime($row['scheduled_at']??$row['deadline_at']))?></span></a><?php endforeach;?><?php if(!$nextSteps):?><p class="empty">未完了の選考はありません。</p><?php endif;?></div>
    </section>
    <section class="panel wide"><div class="section-head"><h2>未完了タスク</h2><button class="button" type="button" data-dialog-open="task-dialog">追加</button></div><div class="stack"><?php foreach($tasks as $row):?><article class="list-card task-row"><span class="status <?=$row['due_at']&&substr($row['due_at'],0,10)<date('Y-m-d')?'danger':'todo'?>"><?=h(fmt_datetime($row['due_at']))?></span><span class="task-main"><strong><?=h($row['title'])?></strong><small><?=h($row['company_name']??'企業未指定')?><?=!empty($row['application_title'])?' / '.h($row['application_title']):''?></small></span><form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="complete_task"><input type="hidden" name="task_id" value="<?=$row['task_id']?>"><button class="button small" type="submit">完了</button></form></article><?php endforeach;?><?php if(!$tasks):?><p class="empty">未完了タスクはありません。</p><?php endif;?></div></section>
    <section class="panel wide"><div class="section-head"><h2>最近のメモ</h2></div><div class="stack"><?php foreach($recentNotes as $row):?><a class="list-card" href="<?=!empty($row['company_id'])?'company.php?id='.(int)$row['company_id']:'#calendar'?>"><span class="status"><?=h($row['category'])?></span><span><strong><?=h($row['title'])?></strong><small><?=h($row['company_name']??'企業未指定')?> / <?=h(fmt_datetime($row['updated_at']))?></small></span></a><?php endforeach;?><?php if(!$recentNotes):?><p class="empty">メモはまだありません。</p><?php endif;?></div></section>
    <section class="panel wide" id="calendar"><div class="section-head"><div><span class="eyebrow">CALENDAR</span><h2>カレンダー</h2></div><div class="hero-actions"><button class="button" type="button" data-dialog-open="availability-dialog">空き日時を探す</button><button class="button primary" type="button" data-open-event>予定を追加</button><form method="get"><input class="field small" type="month" name="month" value="<?=h($calendar['month'])?>" onchange="this.form.submit()"></form></div></div><div class="calendar"><div class="calendar-dow">月</div><div class="calendar-dow">火</div><div class="calendar-dow">水</div><div class="calendar-dow">木</div><div class="calendar-dow">金</div><div class="calendar-dow">土</div><div class="calendar-dow">日</div><?php for($day=$calendar['start'];$day<$calendar['end'];$day=$day->modify('+1 day')):$date=$day->format('Y-m-d');?><button type="button" class="calendar-day <?=$day->format('Y-m')===$calendar['month']?'':'other'?>" data-day-open="<?=h($date)?>"><strong><?=$day->format('j')?></strong><?php foreach(array_slice($calendar['eventsByDate'][$date]??[],0,3) as $event):?><span class="calendar-event <?=$event['schedule_status']==='tentative'?'tentative':''?>"><b><?=h(substr($event['start_at'],11,5))?></b> <?=h($event['title'])?></span><?php endforeach;?><?php if(count($calendar['eventsByDate'][$date]??[])>3):?><small>ほか <?=count($calendar['eventsByDate'][$date])-3?>件</small><?php endif;?></button><?php endfor;?></div></section>
    <?php if($availabilitySearched):?><section class="panel wide availability-results"><div class="section-head"><div><span class="eyebrow">AVAILABLE SLOTS</span><h2>空いている日時</h2></div><button class="button" type="button" data-dialog-open="availability-dialog">条件を変更</button></div><?php if($availability):?><div class="slot-grid"><?php foreach($availability as $slot):?><button class="slot-card" type="button" data-slot-start="<?=h(str_replace(' ','T',substr($slot['start_at'],0,16)))?>" data-slot-end="<?=h(str_replace(' ','T',substr($slot['end_at'],0,16)))?>"><strong><?=h($slot['label'])?></strong><small>予定として登録</small></button><?php endforeach;?></div><?php else:?><p class="empty">指定した条件で空いている日時はありません。</p><?php endif;?></section><?php endif;?>
  </div>
</main>
<dialog id="task-dialog" class="dialog"><form method="post" class="form-stack"><div class="section-head"><h2>タスクを登録</h2><button class="icon-button" type="button" data-dialog-close>×</button></div><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="add_task"><label>タスク名<input class="field" name="title" required placeholder="ESを提出する"></label><label>期限<input class="field" type="datetime-local" name="due_at"></label><label>企業<select class="field" name="company_id"><option value="">企業未指定</option><?php foreach($companies as $row):?><option value="<?=$row['company_id']?>"><?=h($row['name'])?></option><?php endforeach;?></select></label><label>応募案件<select class="field" name="application_id"><option value="">応募案件未指定</option><?php foreach($allApplications as $row):?><option value="<?=$row['application_id']?>"><?=h($row['company_name'].' / '.$row['title'])?></option><?php endforeach;?></select></label><button class="button primary" type="submit">登録</button></form></dialog>
<dialog id="day-dialog" class="dialog calendar-dialog"><div class="section-head"><div><span class="eyebrow">DAY SCHEDULE</span><h2 data-day-title>日別予定</h2></div><div class="hero-actions"><button class="button" type="button" data-day-add>予定を追加</button><button class="icon-button" type="button" data-dialog-close>×</button></div></div><?php foreach($calendar['eventsByDate'] as $date=>$dayEvents):?><div class="day-timeline" data-day-panel="<?=h($date)?>" hidden><?php foreach($dayEvents as $event):?><article class="day-event <?=$event['schedule_status']==='tentative'?'tentative':''?>"><time><?=h(substr($event['start_at'],11,5))?> - <?=h(substr($event['end_at']??$event['start_at'],11,5))?></time><div><div class="event-tags"><span class="status <?=$event['schedule_status']==='tentative'?'todo':'doing'?>"><?=$event['schedule_status']==='tentative'?'仮予定':'確定'?></span><span class="status"><?=h($event['event_type'])?></span></div><h3><?=h($event['title'])?></h3><p><?=h($event['company_name']??'個人予定')?><?=!empty($event['location'])?' / '.h($event['location']):''?></p></div></article><?php endforeach;?></div><?php endforeach;?><p class="empty" data-day-empty hidden>この日の予定はありません。</p></dialog>
<dialog id="event-dialog" class="dialog"><form method="post" class="form-stack"><div class="section-head"><h2>予定を追加</h2><button class="icon-button" type="button" data-dialog-close>×</button></div><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="add_event"><label>状態<select class="field" name="schedule_status"><option value="confirmed">確定予定</option><option value="tentative">仮予定</option></select></label><label>種類<select class="field" name="event_type"><option value="personal">個人予定</option><option value="interview">面接</option><option value="briefing">説明会</option><option value="deadline">締切</option><option value="other">その他</option></select></label><label>タイトル<input class="field" name="title" required></label><label>開始日時<input class="field" type="datetime-local" name="start_at" data-event-start required></label><label>終了日時<input class="field" type="datetime-local" name="end_at" data-event-end></label><label>企業<select class="field" name="company_id"><option value="">企業未指定</option><?php foreach($companies as $row):?><option value="<?=$row['company_id']?>"><?=h($row['name'])?></option><?php endforeach;?></select></label><label>応募案件<select class="field" name="application_id"><option value="">応募案件未指定</option><?php foreach($allApplications as $row):?><option value="<?=$row['application_id']?>"><?=h($row['company_name'].' / '.$row['title'])?></option><?php endforeach;?></select></label><label>場所<input class="field" name="location"></label><label>URL<input class="field" type="url" name="url"></label><label>メモ<textarea class="field" name="memo"></textarea></label><button class="button primary" type="submit">登録</button></form></dialog>
<dialog id="availability-dialog" class="dialog"><form method="post" class="form-stack"><div class="section-head"><div><span class="eyebrow">SCHEDULING ASSISTANT</span><h2>空き日時を探す</h2></div><button class="icon-button" type="button" data-dialog-close>×</button></div><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="find_availability"><div class="form-grid-2"><label>開始日<input class="field" type="date" name="date_from" value="<?=date('Y-m-d')?>" required></label><label>終了日<input class="field" type="date" name="date_to" value="<?=date('Y-m-d',strtotime('+7 days'))?>" required></label><label>予定の所要時間（分）<input class="field" type="number" name="duration" min="15" max="480" step="15" value="60" required></label><label>候補間隔（分）<select class="field" name="interval"><option value="15">15分</option><option value="30" selected>30分</option><option value="60">60分</option></select></label><label>予定前に空ける時間（分）<input class="field" type="number" name="buffer_before" min="0" max="180" step="5" value="15"></label><label>予定後に空ける時間（分）<input class="field" type="number" name="buffer_after" min="0" max="180" step="5" value="15"></label><label>検索開始時刻<input class="field" type="time" name="work_start" value="09:00" required></label><label>検索終了時刻<input class="field" type="time" name="work_end" value="18:00" required></label></div><label class="check"><input type="checkbox" name="include_weekends"> 土日も候補に含める</label><p class="muted">確定予定と仮予定の両方を避けて候補を出します。</p><button class="button primary" type="submit">候補を出す</button></form></dialog>
<script src="assets/js/calendar.js" defer></script>
<?php require __DIR__.'/layout/end.php'; ?>
