<?php require __DIR__.'/layout/start.php'; ?>
<main class="shell">
  <section class="hero compact"><div><span class="eyebrow">KNOWLEDGE</span><h1>メモ・カンペ</h1><p>関連先なしでも保存でき、必要なメモだけをセッションモードで確認できます。</p></div><div class="hero-actions"><a class="button" href="notes.php<?=$trash?'':'?trash=1'?>"><?=$trash?'メモ一覧へ戻る':'ゴミ箱'?></a><?php if(!$trash):?><button class="button primary" data-dialog-open="note-dialog">メモを追加</button><?php endif;?></div></section>
  <section class="panel"><form class="search" method="get"><?php if($trash):?><input type="hidden" name="trash" value="1"><?php endif;?><input class="field" name="q" value="<?=h($q)?>" placeholder="本文・タグ・会社・応募案件を検索"><button class="button">検索</button></form>
    <div class="note-board"><?php foreach($notes as $note):?><article class="content-card note-card"><div class="section-head"><div><span class="status"><?=h($note['tag_names']?:'分類未設定')?></span><?php if($note['interview_visible']):?><span class="status doing">カンペ表示</span><?php endif;?></div><small><?=h($note['company_name']??'関連先なし')?><?=!empty($note['application_title'])?' / '.h($note['application_title']):''?></small></div><h2><?=h($note['title'])?></h2><p><?=nl2br(h(mb_strimwidth($note['body'],0,420,'…')))?></p><div class="hero-actions"><?php if($trash):?><form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="restore"><input type="hidden" name="note_id" value="<?=$note['note_id']?>"><input type="hidden" name="trash_view" value="1"><button class="button">復元</button></form><?php else:?><button class="button small" data-dialog-open="edit-note-<?=$note['note_id']?>">編集</button><form method="post"><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="trash"><input type="hidden" name="note_id" value="<?=$note['note_id']?>"><button class="button small">ゴミ箱へ</button></form><?php endif;?></div></article>
    <?php if(!$trash):?><dialog id="edit-note-<?=$note['note_id']?>" class="dialog"><form method="post" class="form-stack"><div class="section-head"><h2>メモを編集</h2><button type="button" class="icon-button" data-dialog-close>×</button></div><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="update"><input type="hidden" name="note_id" value="<?=$note['note_id']?>"><label>タイトル<input class="field" name="title" value="<?=h($note['title'])?>" required></label><label>本文<textarea class="field tall" name="body" required><?=h($note['body'])?></textarea></label><label class="check"><input type="checkbox" name="interview_visible" <?=$note['interview_visible']?'checked':''?>> セッションモードでカンペ表示</label><button class="button primary">保存</button></form></dialog><?php endif;?><?php endforeach;?><?php if(!$notes):?><p class="empty"><?=$trash?'ゴミ箱は空です。':'メモはまだありません。'?></p><?php endif;?></div>
  </section>
</main>
<?php if(!$trash):?><dialog id="note-dialog" class="dialog"><form method="post" class="form-stack"><div class="section-head"><h2>メモを追加</h2><button type="button" class="icon-button" data-dialog-close>×</button></div><input type="hidden" name="csrf_token" value="<?=h(csrf_token())?>"><input type="hidden" name="action" value="add"><label>会社<select class="field" name="company_id"><option value="">関連先なし（共通メモ）</option><?php foreach($companies as $c):?><option value="<?=$c['company_id']?>"><?=h($c['name'])?></option><?php endforeach;?></select></label><label>応募案件<select class="field" name="application_id"><option value="">指定しない</option><?php foreach($applications as $a):?><option value="<?=$a['application_id']?>"><?=h($a['company_name'].' / '.$a['title'])?></option><?php endforeach;?></select></label><label>タイトル<input class="field" name="title" required></label><label>本文<textarea class="field tall" name="body" required></textarea></label><fieldset class="tag-picker"><legend>タグ（未設定でも保存できます）</legend><?php foreach($tags as $tag):?><label class="check"><input type="checkbox" name="tag_ids[]" value="<?=$tag['tag_id']?>"> <?=h($tag['name'])?></label><?php endforeach;?></fieldset><label class="check"><input type="checkbox" name="interview_visible"> セッションモードでカンペ表示</label><button class="button primary">保存</button></form></dialog><?php endif;?>
<?php require __DIR__.'/layout/end.php'; ?>
